"""User model added

Revision ID: 637328eaf467
Revises: 50ed308560a0
Create Date: 2023-04-08 17:41:04.786027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637328eaf467'
down_revision = '50ed308560a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_donation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_user_id_user', type_='foreignkey')

    # ### end Alembic commands ###
